'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),vm=require('node:vm');
const {EventEmitter}=require('node:events'),{createRequire}=require('node:module'),{createHash}=require('node:crypto');
const bytes=Buffer.from('MZinert-main-upgrade-fixture');
const data={id:71,tag_name:'v1.1.0',html_url:'https://github.com/zeidlern/NerdSSHell/releases/tag/v1.1.0',draft:false,prerelease:false,published_at:'2026-10-08T12:00:00Z',assets:[{id:72,name:'NerdSSHell-1.1.0-x64-Setup.exe',state:'uploaded',size:bytes.length,digest:'sha256:'+createHash('sha256').update(bytes).digest('hex'),browser_download_url:'https://github.com/zeidlern/NerdSSHell/releases/download/v1.1.0/NerdSSHell-1.1.0-x64-Setup.exe'}]};
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function until(value){for(let n=0;n<300;n++){if(value())return;await delay(10)}throw new Error('Synthetic update-main wait failed')}
async function fixture(t,settings={}){
 const directory=fs.mkdtempSync(path.join(os.tmpdir(),'nerdsshell-update-main-'));const handlers=new Map(),events=[],requests=[],handoffs=[];let win;
 const app=new EventEmitter();Object.assign(app,{isPackaged:settings.packaged!==false,getPath:()=>directory,setPath(){},getVersion:()=>settings.version||'1.0.4',commandLine:{getSwitchValue:name=>name==='user-data-dir'?directory:name==='remote-debugging-port'&&settings.debug?'9222':''},requestSingleInstanceLock:()=>true,whenReady:()=>Promise.resolve(),setAppUserModelId(){},quit(){const e={preventDefault(){this.prevented=true}};app.emit('before-quit',e);if(!e.prevented)app.finished=(app.finished||0)+1;},exit(){throw new Error('Unexpected startup exit')}});
 class Window extends EventEmitter{constructor(){super();win=this;this.webContents=new EventEmitter();Object.assign(this.webContents,{mainFrame:{url:'nerdsshell://app/ui/index.html'},send:(_channel,e)=>events.push(e),setWindowOpenHandler(){},session:{setPermissionRequestHandler(){},setPermissionCheckHandler(){}}});}isDestroyed(){return false}isMinimized(){return false}flashFrame(){}focus(){}loadURL(){this.webContents.emit('did-finish-load');return Promise.resolve()}}
 const filename=path.resolve(__dirname,'../src/main.cjs'),actual=createRequire(filename);
 const electron={app,BrowserWindow:Window,ipcMain:{handle:(name,fn)=>handlers.set(name,fn)},dialog:{showErrorBox(){throw new Error('Unexpected native startup error')}},clipboard:{},Menu:{setApplicationMenu(){}},shell:{},protocol:{registerSchemesAsPrivileged(){},handle(){}},net:{async fetch(url,options){requests.push({url,options});return url.includes('/releases/latest')?new Response(JSON.stringify(data)):new Response(bytes);}},safeStorage:{isEncryptionAvailable:()=>false}};
 const context=vm.createContext({require:name=>name==='electron'?electron:name==='./update-handoff.cjs'?{async armUpdate(plan){const handoff={plan,releases:0,cancels:0,async release(){this.releases++},async cancel(){this.cancels++}};handoffs.push(handoff);if(settings.armGate)await settings.armGate;return handoff;}}:actual(name),__dirname:path.dirname(filename),Buffer,process:{...process,platform:'win32',arch:'x64',execPath:path.join(directory,'NerdSSHell.exe')},console,setTimeout,clearTimeout});
 vm.runInContext(fs.readFileSync(filename,'utf8'),context,{filename});await until(()=>win&&handlers.has('nerdsshell:state'));
 const reply=(e,value)=>handlers.get('nerdsshell:promptReply')({sender:win.webContents,senderFrame:win.webContents.mainFrame},e.id,value);
 const state=()=>vm.runInContext('({quitting,quitPending,updater:startupUpdater,connections})',context);
 const addRemote=(count=1)=>{context.fixtureRemote={connected:true,client:{},shells:new Map(count?[['shell',{dead:false}]]:[]),activeShellCount:()=>count,disconnects:0,disconnect(){this.disconnects++;this.connected=false}};vm.runInContext("connections.set('fixture',{profile:{id:'fixture',sessionMode:'persistent'},remote:fixtureRemote,wanted:true,secrets:{}})",context);return context.fixtureRemote};
 t.after(async()=>{await state().updater?.cancel(true);for(const h of handoffs){if(fs.existsSync(h.plan.stageDirectory))fs.rmSync(h.plan.stageDirectory,{recursive:true,force:true})}fs.rmSync(directory,{recursive:true,force:true})});
 return{app,win,events,requests,handoffs,reply,state,addRemote,context};
}
const updateEvent=value=>value.events.find(e=>e.type==='prompt'&&e.title==='NerdSSHell update available');
test('actual main startup offers Upgrade/Not now once in the shared trusted dialog',async t=>{
 const value=await fixture(t);await until(()=>updateEvent(value));const e=updateEvent(value);assert.deepEqual(Array.from(e.buttons),['Upgrade','Not now']);assert.equal(e.cancelId,1);assert.equal(e.defaultId,1);assert.equal('signal'in e,false);assert.equal('valid'in e,false);assert.equal(e.rememberPasswordAvailable,false);
 await value.reply(e,'choice:1');await value.state().updater.task;assert.equal(value.requests.length,1);assert.equal(value.handoffs.length,0);assert.equal(value.app.finished,undefined);
 value.win.webContents.emit('did-finish-load');await delay(10);assert.equal(value.requests.length,1);
});
test('actual source/debug startup never contacts GitHub',async t=>{for(const settings of [{packaged:false},{debug:true}]){const value=await fixture(t,settings);await delay(20);assert.equal(value.requests.length,0)}});
test('actual accepted main update invokes normal quit and acknowledged installer handoff',async t=>{
 const value=await fixture(t);await until(()=>updateEvent(value));await value.reply(updateEvent(value),'choice:0');await until(()=>value.app.finished===1).catch(error=>{console.log(JSON.stringify({notices:value.events.filter(e=>e.type==='notice').map(e=>e.message),handoffs:value.handoffs.map(h=>({releases:h.releases,cancels:h.cancels})),quitting:value.state().quitting,aborted:value.state().updater.controller.signal.aborted}));throw error});assert.equal(value.requests.length,2);assert.equal(value.handoffs.length,1);assert.equal(value.handoffs[0].releases,1);assert.equal(value.handoffs[0].cancels,0);assert.equal(value.state().quitting,true);
 await assert.rejects(value.reply(updateEvent(value),'choice:0'),/closing/);
});
test('actual Standard quit cancellation keeps remote work and never starts installer',async t=>{
 const value=await fixture(t);const remote=value.addRemote();await until(()=>updateEvent(value));await value.reply(updateEvent(value),'choice:0');await until(()=>value.events.some(e=>e.title==='Close nonpersistent consoles?'));const consent=value.events.find(e=>e.title==='Close nonpersistent consoles?');await value.reply(consent,'choice:1');await until(()=>!value.state().quitPending);
 assert.equal(remote.disconnects,0);assert.equal(value.handoffs.length,0);assert.equal(value.app.finished,undefined);assert.equal(value.state().updater.ready,null);
});
test('actual unsaved Scratchpad refusal preserves notes and cancels update',async t=>{
 const value=await fixture(t);value.app.nerdsshellScratchpadDirty=true;value.app.nerdsshellScratchpadRevision=4;await until(()=>updateEvent(value));await value.reply(updateEvent(value),'choice:0');await until(()=>value.events.some(e=>e.title==='Discard unsaved scratchpad?'));await value.reply(value.events.find(e=>e.title==='Discard unsaved scratchpad?'),'choice:1');await until(()=>!value.state().quitPending);assert.equal(value.app.nerdsshellScratchpadDirty,true);assert.equal(value.handoffs.length,0);assert.equal(value.app.finished,undefined);
});
test('main revalidates new work after slow handoff preparation and cancels stale approval',async t=>{
 let release;const armGate=new Promise(resolve=>release=resolve);const value=await fixture(t,{armGate});const remote=value.addRemote();await until(()=>updateEvent(value));await value.reply(updateEvent(value),'choice:0');await until(()=>value.events.some(e=>e.title==='Close nonpersistent consoles?'));await value.reply(value.events.find(e=>e.title==='Close nonpersistent consoles?'),'choice:0');await until(()=>value.handoffs.length===1);remote.shells.set('new-shell',{dead:false});release();await until(()=>!value.state().quitPending);assert.equal(remote.disconnects,0);assert.equal(value.handoffs[0].releases,0);assert.equal(value.handoffs[0].cancels,1);assert.equal(value.app.finished,undefined);
});
test('renderer reload aborts its updater prompt without accepting or exiting',async t=>{const value=await fixture(t);await until(()=>updateEvent(value));value.win.webContents.emit('did-start-loading');await value.state().updater.task;assert.equal(value.handoffs.length,0);assert.equal(value.app.finished,undefined);assert.equal(value.requests.length,1);assert.ok(value.events.some(e=>e.type==='promptCancelled'))});
