'use strict';
const { contextBridge, ipcRenderer, webUtils } = require('electron');
const invoke = name => (...args) => ipcRenderer.invoke('nerdsshell:' + name, ...args);
const api = {};
api.publicLink = invoke('publicLink');
api.forgetPassword = invoke('forgetPassword');
for (const name of ['quickConnect', 'quickConnectDefaults', 'quickConnectClearHistory', 'quickConnectSave']) api[name] = invoke(name);
for (const name of ['state', 'savePreferences', 'sessionAttention', 'activeSession', 'paneActionRun', 'saveProfile', 'saveAppearance', 'deleteProfile', 'connect', 'disconnect', 'discover', 'open', 'close', 'input', 'resize', 'create', 'rename', 'end', 'snapshot', 'workspace', 'promptReply', 'ack', 'chooseKey', 'copy', 'paste', 'fullscreen', 'history', 'export', 'cancelTransfer', 'dataFolder', 'listFiles', 'cancelFileList', 'downloadFile', 'workbenchContext', 'workbenchPreferences', 'localOpen', 'workbenchActions', 'workbenchDetect', 'workbenchTemplate', 'workbenchReview', 'workbenchCancelReview', 'workbenchRun', 'inputLock', 'workbenchDiagnostics', 'localAdminOpen', 'scratchpadDirty', 'scratchpadRead', 'scratchpadSave', 'actionConfiguration', 'actionConfigurationSave', 'actionNewId', 'actionTemplates', 'actionPreview', 'paneActions', 'localFilesList', 'localFilesChoose', 'localFilesUpload', 'localFilesDownload']) api[name] = invoke(name);
api.chooseUpload = key => ipcRenderer.invoke('nerdsshell:upload', key, null);
api.dropUpload = (key, files) => ipcRenderer.invoke('nerdsshell:upload', key, files.map(file => webUtils.getPathForFile(file)));
api.browserUpload = (key, directory, files) => ipcRenderer.invoke('nerdsshell:browserUpload', key, directory, files === null ? null : files.map(file => webUtils.getPathForFile(file)));
api.filePaths = files => files.map(file => webUtils.getPathForFile(file));
api.onEvent = callback => { const handler = (_event, data) => callback(data); ipcRenderer.on('nerdsshell:event', handler); return () => ipcRenderer.removeListener('nerdsshell:event', handler); };
contextBridge.exposeInMainWorld('nerdsshell', Object.freeze(api));
